### PR TITLE
syncing test of git with test of github

### PR DESCRIPTION
**Pull request by me-nobody**
please review

### CODE REVIEW

**Comment by me-nobody** [comment]
please review

**Review by matcha-coding — APPROVED** [review]

**Review by ankitthakur007 — APPROVED** [review]
Done from my side

**Review by sillyfalcon — APPROVED** [review]
Delete files??

**Review by matcha-coding — APPROVED** [review]
I am approving it.

**Comment by me-nobody** [comment]
we checked from main to a branch
we deleted all unnecessary files
on the branch we did git add git commit git push and push to branch of git hub
then we issued a pull request for merging branch to main
after approval we are merging

**Pull request closed without merging**
