### PR TITLE
Created common_file.txt

### PR DESCRIPTION
**Pull request by me-nobody**
This is the common file for practise on 22/5/21. it is a blank file. please review and allow for merging to main

### CODE REVIEW

**Review by matcha-coding — APPROVED** [review]
Hi Anubrata.
I am approving your request.

Mateus

**Review by ankitthakur007 — APPROVED** [review]
Done, from my side, and I m approving this pull requests using my mobile 📱. 😇🙂🙃

**Comment by me-nobody** [comment]
thank you buddies. marching on for editing common file

**Comment by sillyfalcon** [comment]
This is fine! Sorry for the delay

**Pull request merged**
